### ISSUE TITLE
Mac Os Wallet: SpectreSecurityCoin-Qt cannot be opened because of a problem

### ISSUE THREAD

**Issue by cryptofranco** [SpectreSecurityCoin/SpectreSecurityCoin#7]
Process:               SpectreSecurityCoin-Qt [32156]
Path:                  /Volumes/VOLUME/SpectreSecurityCoin Qt.app/Contents/MacOS/SpectreSecurityCoin-Qt
Identifier:            co.SpectreSecurityCoin.SpectreSecurityCoin-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SpectreSecurityCoin-Qt [32156]
User ID:               501

Date/Time:             2019-03-31 04:50:45.452 +0100
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        0A634F37-DD14-D08F-E2D9-7E8B00C80ADB

Sleep/Wake UUID:       E501847A-3B42-4539-BB5D-DEEB463145B0

Time Awake Since Boot: 12000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib
  Referenced from: /Volumes/VOLUME/SpectreSecurityCoin-Qt.app/Contents/MacOS/SpectreSecurityCoin-Qt
  Reason: image not found

Binary Images:
       0x10c309000 -        0x10cb2aff3 +co.SpectreSecurityCoin.SpectreSecurityCoin-Qt (0) <7EEB9C02-B725-3EB3-8486-1356EE94F656> /Volumes/VOLUME/SpectreSecurityCoin-Qt.app/Contents/MacOS/SpectreSecurityCoin-Qt
       0x10db52000 -        0x10dbd0a87  dyld (655.1) <3EBA447F-A546-366B-B302-8DC3B21A3E30> /usr/lib/dyld

Model: MacBookPro12,1, BootROM 180.0.0.0.0, 2 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464132333241324D412D4A442D460000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.61.1 AirPortDriverBrcmNIC-1305.2)
Bluetooth: Version 6.0.10f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by SpectreSecurity** [comment]
Yes, we are working on this currently. We had an update in the build env that produced the dmg. We will upload a new DMG for mac os to fix this soon.

One workaround is to install the dependacys , or ( build your own qt version ) as these are installed for you during the build process. These files are bundled in the DMG as embeded objects.

**Comment by SpectreSecurity** [comment]
Please try the new DMG. Its in the release seaction.
